<?php
/**
 * @file
 * Code for the eventbrite import feature.
 */

include_once 'drupalaton_eventbrite_import.features.inc';

/**
 * Implements hook_feeds_plugins().
 */
function drupalaton_eventbrite_import_feeds_plugins() {
  $path = drupal_get_path('module', 'drupalaton_eventbrite_import') . '/plugins';

  $info['FeedsUserExtendedProcessor'] = array(
    'name' => 'User extended processor',
    'description' => 'Create users and send account mails.',
    'help' => 'Create users from parsed content.',
    'handler' => array(
      'parent' => 'FeedsUserProcessor',
      'class' => 'FeedsUserExtendedProcessor',
      'file' => 'FeedsUserExtendedProcessor.inc',
      'path' => $path,
    ),
  );

  return $info;
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function drupalaton_eventbrite_import_form_user_profile_form_alter(&$form, $form_state, $form_id) {
  if (isset($form['account']['mail'])) {
    if (!in_array('administrator', $GLOBALS['user']->roles)) {
      $form['account']['mail']['#access'] = FALSE;
    }
  }
}
